import React from "react";
import { Tile } from "../Tile";

export function Grid6() {
  return (
    <>
      <Tile
        gridColumn={19}
        gridColumnSpan={6}
        gridRow={1}
        gridRowSpan={8}
        imgSrc="/images/car37.jpg"
      />
      <Tile
        gridColumn={1}
        gridColumnSpan={9}
        gridRow={1}
        gridRowSpan={8}
        imgSrc="/images/car32.jpg"
      />
      <Tile
        gridColumn={10}
        gridColumnSpan={5}
        gridRow={6}
        gridRowSpan={3}
        imgSrc="/images/car33.jpg"
      />
      <Tile
        gridColumn={1}
        gridColumnSpan={9}
        gridRow={9}
        gridRowSpan={4}
        imgSrc="/images/car34.jpg"
      />
      <Tile
        gridColumn={10}
        gridColumnSpan={9}
        gridRow={1}
        gridRowSpan={5}
        imgSrc="/images/car38.jpg"
      />
      <Tile
        gridColumn={10}
        gridColumnSpan={5}
        gridRow={9}
        gridRowSpan={4}
        imgSrc="/images/car36.jpg"
      />
      <Tile
        gridColumn={15}
        gridColumnSpan={4}
        gridRow={6}
        gridRowSpan={3}
        imgSrc="/images/car39.jpg"
      />
      <Tile
        gridColumn={15}
        gridColumnSpan={10}
        gridRow={9}
        gridRowSpan={4}
        imgSrc="/images/car40.jpg"
      />
    </>
  );
}
